## Group by

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("census.csv")
df = df[df["SUMLEV"] == 50]
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [17]:
"""
%%timeit -n 10
for state in df["STNAME"].unique():
    avg = np.average(df.where(df["STNAME"] == state).dropna()["CENSUS2010POP"])
    print("Counties in state" + state + "have an average population of" + str(avg))
"""

'\n%%timeit -n 10\nfor state in df["STNAME"].unique():\n    avg = np.average(df.where(df["STNAME"] == state).dropna()["CENSUS2010POP"])\n    print("Counties in state" + state + "have an average population of" + str(avg))\n'

In [18]:
"""
%%timeit -n 10
for group, frame in df.groupby("STNAME"):
    avg = np.average(frame["CENSUS2010POP"])
    print("Counties in state" + group + "have an average population of" + str(avg))
    """

'\n%%timeit -n 10\nfor group, frame in df.groupby("STNAME"):\n    avg = np.average(frame["CENSUS2010POP"])\n    print("Counties in state" + group + "have an average population of" + str(avg))\n    '

In [19]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [20]:
df = df.set_index("STNAME")
def fun(item):
    if item[0] < "M":
        return 0
    if item[0] > "Q":
        return 1
    return 2
for group, frame in df.groupby(fun):
    print("There are " + str(len(frame)) + " records in group " + str(group) + " for processing.")

There are 1177 records in group 0 for processing.
There are 831 records in group 1 for processing.
There are 1134 records in group 2 for processing.

In [21]:
df = pd.read_csv("census.csv")
df = df[df["SUMLEV"] == 50]

In [22]:
df.groupby("STNAME").agg({"CENSUS2010POP" : np.average})

                      CENSUS2010POP
STNAME
Alabama                71339.343284
Alaska                 24490.724138
Arizona               426134.466667
Arkansas               38878.906667
California            642309.586207
Colorado               78581.187500
Connecticut           446762.125000
Delaware              299311.333333
District of Columbia  601723.000000
Florida               280616.567164
Georgia                60928.635220
Hawaii                272060.200000
Idaho                  35626.863636
Illinois              125790.509804
Indiana                70476.108696
Iowa                   30771.262626
Kansas                 27172.552381
Kentucky               36161.391667
Louisiana              70833.937500
Maine                  83022.562500
Maryland              240564.666667
Massachusetts         467687.785714
Michigan              119080.000000
Minnesota              60964.655172
Mississippi            36186.548780
Missouri               52077.626087
Montana                17668.125000
Nebraska               19638.075269
Nevada                158855.941176
New Hampshire         131647.000000
New Jersey            418661.619048
New Mexico             62399.363636
New York              312550.032258
North Carolina         95354.830000
North Dakota           12690.396226
Ohio                  131096.636364
Oklahoma               48718.844156
Oregon                106418.722222
Pennsylvania          189587.746269
Rhode Island          210513.400000
South Carolina        100551.391304
South Dakota           12336.060606
Tennessee              66801.105263
Texas                  98998.271654
Utah                   95306.379310
Vermont                44695.785714
Virginia               60111.293233
Washington            172424.102564
West Virginia          33690.800000
Wisconsin              78985.916667
Wyoming                24505.478261

In [28]:
print(type(df.groupby(level = 0)["POPESTIMATE2010", "POPESTIMATE2011"]))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

<ipython-input-28-ecd635e3d94f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  print(type(df.groupby(level = 0)["POPESTIMATE2010", "POPESTIMATE2011"]))

In [25]:
print(type(df.groupby(level = 0)["POPESTIMATE2010"]))
#(df.set_index('STNAME').groupby(level = 0)['CENSUS2010POP'].agg({'avg': np.average, 'sum': np.sum}))

In [35]:
#(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011'].agg({'avg': np.average, 'sum': np.sum}))

In [36]:
#(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011'].agg({'POPESTIMATE2010': np.average, 'POPESTIMATE2011': np.sum}))

## Test
> Looking at our backpacking equipment DataFrame, suppose we are interested in finding our total weight for each category. Use groupby to group the dataframe, and apply a function to calculate the total weight (Weight x Quantity) by category

```print(df.groupby("Category").apply(lambda df, a, b : sum(df[a] * df[b]),"Weight(oz.)", "Quantity"))```